#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

restore0Dir

runApplication setFields
runApplication decomposePar -force
mv log.decomposePar log.decomposeParRun
runParallel renumberMesh -overwrite -parallel 

runParallel $(getApplication) 

runApplication reconstructPar -latestTime
runApplication postProcess -latestTime

# runApplication decomposePar -force
# mv log.decomposePar log.decomposeParRun
# runParallel renumberMesh -overwrite -parallel 

# runParallel $(getApplication)
# & pyFoamPlotWatcher.py --with-courant --with-deltat --with-iterations \
     # --progress \
     # log.$(getApplication)



#------------------------------------------------------------------------------
