#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

runApplication blockMesh
runApplication decomposePar -force
mv log.decomposePar log.decomposeParMesh
runParallel snappyHexMesh -overwrite

runApplication reconstructParMesh -constant
runApplication topoSet
runApplication createPatch -overwrite
runApplication renumberMesh -overwrite
#------------------------------------------------------------------------------
